bakery/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('breadapp.urls'))
]

breadapp/urls.py
from django.urls import path
from .views import *

app_name = "breadapp"

urlpatterns = [
    path('', bakery_home, name='bakery_home'),
    path('list/', bakery_list, name='bakery_list'),
    path('bread/<int:bread_id>', bread_details, name='bread_details'),
    path('inside/', bakery_inside, name='bakery_inside')

]

breadapp/models/bread.py
from django.db import models
from django.urls import reverse


class Bread(models.Model):

    name = models.CharField(max_length=100)
    region = models.CharField(max_length=100)
    ingredients = models.ManyToManyField("Ingredient", through='BreadIngredient')

    class Meta:
        verbose_name = ("Bread")
        verbose_name_plural = ("Breads")

    def __str__(self):
        return f"{self.name} ({self.region})"

    def get_absolute_url(self):
        return reverse("Bread_detail", kwargs={"pk": self.pk})

breadapp/models/bread_ingredient.py
from django.db import models


class BreadIngredient(models.Model):

    bread = models.ForeignKey("Bread", on_delete=models.CASCADE)
    ingredient = models.ForeignKey("Ingredient", on_delete=models.CASCADE)
    amount = models.CharField(max_length=25)

breadapp/models/ingredient.py
from django.db import models
from django.urls import reverse


class Ingredient(models.Model):

    name = models.CharField(max_length=100)
    local_source = models.CharField(max_length=100)
    breads = models.ManyToManyField("Bread", through='BreadIngredient')

    class Meta:
        verbose_name = ("Ingredient")
        verbose_name_plural = ("Ingredients")

    def __str__(self):
        return f"{self.name} ({self.local_source})"

    def get_absolute_url(self):
        return reverse("Ingredient_detail", kwargs={"pk": self.pk})

breadapp/views/bakery_home.py
from .connection import Connection
from django.shortcuts import render, redirect, reverse
import sqlite3
from ..models import Bread

def bakery_home(request):
    if request.method == 'GET':
        template = 'bakery_home.html'

        return render(request, template)
    

breadapp/views/bakery_list.py
from .connection import Connection
from django.shortcuts import render, redirect, reverse
import sqlite3
from ..models import Bread

def get_bread():
    with sqlite3.connect(Connection.db_path) as conn:
        conn.row_factory = sqlite3.Row
        db_cursor = conn.cursor()
        db_cursor.execute("""
        SELECT
            b.id,
            b.name,
            b.region
        FROM breadapp_bread AS b
        ORDER BY b.name
        """)

        resp = db_cursor.fetchall()
        bread_inventory = []
        for i, item in enumerate(resp):
            bread = Bread()
            bread.id = item['id']
            bread.number = i + 1
            bread.name = item['name']
            bread.region = item['region']
            bread_inventory.append(bread)

        return bread_inventory

def post_bread(request):
    form_data = request.POST
    with sqlite3.connect(Connection.db_path) as conn:
        db_cursor = conn.cursor()
        db_cursor.execute("""
        INSERT INTO breadapp_bread
        (name, region)
        VALUES (?, ?)
        """,
        (form_data['breadName'], form_data['breadRegion']))
    return redirect(reverse('breadapp:bakery_list'))

def bakery_list(request):
    if request.method == 'GET':
        bread_inventory = get_bread()
        template = 'bakery_list.html'
        context = {
            'bread_inventory': bread_inventory
        }

        return render(request, template, context)
    
    elif request.method == 'POST':
        return post_bread(request)

def bakery_inside(request):
    if request.method == 'GET':
        bread_inventory = get_bread()
        template = 'bakery_inside.html'
        context = {
            'bread_inventory': bread_inventory
        }

        return render(request, template, context)
    
    elif request.method == 'POST':
        return post_bread(request)

breadapp/views/bread_details.py
from .connection import Connection
from django.shortcuts import render, redirect, reverse
import sqlite3
from ..models import Bread, Ingredient


def get_bread(bread_id):
    with sqlite3.connect(Connection.db_path) as conn:
        conn.row_factory = sqlite3.Row
        db_cursor = conn.cursor()
        db_cursor.execute("""
        SELECT
            b.id,
            b.name,
            b.region,
            bi.amount,
            i.name AS i_name,
            i.local_source
        FROM breadapp_bread AS b
        LEFT JOIN breadapp_breadingredient AS bi ON bi.bread_id = b.id
        LEFT JOIN breadapp_ingredient as i ON bi.ingredient_id = i.id
        WHERE b.id = ?
        """, (bread_id,))

        response = db_cursor.fetchall()

        for row in response:
            print("ROW!!!!!!")
            print(row)            
        bread = Bread()
        bread.ingredient_list = []
        for row in response:
            if row == response[0]:
                bread.id = row['id']
                bread.name = row['name']
                bread.region = row['region']
                if not row['i_name'] == None:
                    ingredient = Ingredient()
                    ingredient.name = row['i_name']
                    ingredient.local_source = row['local_source']
                    bread.ingredient_list.append(ingredient)
            else:
                ingredient = Ingredient()
                ingredient.name = row['i_name']
                ingredient.amount = row['amount']
                ingredient.local_source = row['local_source']
                bread.ingredient_list.append(ingredient)
        
        bread.length = len(bread.ingredient_list)
        return bread
        
        

def bread_details(request, bread_id):
    if request.method == 'GET':
        bread = get_bread(bread_id)

        template = 'bread_details.html'
        context = {
            'bread': bread,
        }

        return render(request, template, context)

breadapp/templates/bakery_home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div id='homeBackground' class="backgroundImage" >
    <a href="{% url 'breadapp:bakery_list' %}">
    <img id='easelAfar' src="../static/images/easelAfar.png" alt="">
    </a>
    <img id='mrToastHome' src="../static/images/mrToast.png" alt="">
    <div id='mrToastMessageHome'></div>
    <a id="doorLinkHome" href="{% url 'breadapp:bakery_inside' %}"></a>
</div>

{% endblock %}

breadapp/templates/bakery_inside.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div id='insideBackground' class="backgroundImage" >
    <a href="{% url 'breadapp:bakery_list' %}">
    <img id='menuBoard' src="../static/images/insideMenuBoard.jpg" alt="">
    </a>
    <div id="insideMessage"></div>
    <img id='mrToastInside' src="../static/images/mrToast.png" alt="">
    <!-- <img id='mrToastMessageHome' src="../static/images/mrToastMessageHome.png"> -->
    <a id="doorLinkHome" href="{% url 'breadapp:bakery_list' %}"></a>
</div>

{% endblock %}

breadapp/templates/bakery_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="listBackground" class="backgroundImage">
    <article class="breadList">
    <h3>Our Current Selection</h3>
    {% for bread in bread_inventory %}
        <p>{{bread.number}}. {{bread.name}} from {{bread.region}}  <a onclick='toggleButton()' target='detailsFrame' href='{% url "breadapp:bread_details" bread.id %}'><img class="listImage" src="{% static 'images/bread.png' %}"></a></p>
    {% endfor %}
    </article>
    <article class="addBreadForm">
    <h4>Add Bread to Our Collection!</h4>
    <form class='addBread' action="{% url 'breadapp:bakery_list' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <label for="breadName">Bread: </label>
            <input id="breadName" name="breadName" type="text" placeholder="name" required>
        </fieldset>
        <fieldset>
            <label for="breadRegion">from: </label>
            <input id="breadRegion" name="breadRegion" type="text" placeholder="region" required>
        </fieldset>
        <input type="submit" value="Add Bread">
    </form>
    </article>  
</div>
<div id="greyBackground" class="hidden">
    <section id="detailsFrameContainer">
        <div class="formExit" onclick="toggleButton()">X</div>
        <iframe id="detailsFrame" name="detailsFrame"></iframe>
    </section>
</div>

{% block javascript %}
    <script>
        function toggleButton(){
            document.getElementById('greyBackground').classList.toggle('hidden')
        }
    </script>
{% endblock %}
{% endblock %}

breadapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Bangazon Workforce Management</title>

    <link rel="stylesheet" href="{% static 'styles/base.css' %}" type="text/css" media="screen" />
    <link rel="stylesheet" href="{% static 'styles/navbar.css' %}" type="text/css" media="screen" />
    <link rel="stylesheet" href="{% static 'styles/forms.css' %}" type="text/css" media="screen" />
    <link rel="stylesheet" href="{% static 'styles/home.css' %}" type="text/css" media="screen" />
    <link rel="stylesheet" href="{% static 'styles/list.css' %}" type="text/css" media="screen" />
    <link rel="stylesheet" href="{% static 'styles/inside.css' %}" type="text/css" media="screen" />

    {% block css %}
    {% endblock %}
    
</head>

<body>

    <nav id="navContainer">
        <a href="{% url 'breadapp:bakery_home' %}"><img id='logo' src="../static/images/bread.png" alt="bread"></a>
        <div id="navLinkContainer">
            
        </div>
    </nav>

    <div id="mainContainer" >
        {% block content %}
        {% endblock %}

        {% block scripts %}
        {% endblock scripts %}

    </div>  

</body>

</html>

breadapp/templates/bread_details.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/base.css' %}" type="text/css" media="screen" />
    <link rel="stylesheet" href="{% static 'styles/navbar.css' %}" type="text/css" media="screen" />
    <link rel="stylesheet" href="{% static 'styles/forms.css' %}" type="text/css" media="screen" />
    <link rel="stylesheet" href="{% static 'styles/home.css' %}" type="text/css" media="screen" />
    <link rel="stylesheet" href="{% static 'styles/list.css' %}" type="text/css" media="screen" />
    <title>Details</title>
</head>
<body>
    <div class='altBackground'>
        <section class="detailsContainer">
            <h1>{{bread.name}}</h1>
            <p>({{bread.region}})</p>
            <br>
            {% if bread.length > 0 %}
                <div class="ingredientsContainer">
                    <h4>Ingredients:</h4>
                    {% for ingredient in bread.ingredient_list %}
                        <article class="ingredient">
                        <p><em>{{ingredient.amount}}</em> {{ingredient.name}} from {{ingredient.local_source}}</p>
                        </article>
                    {% endfor %}
                </div>
            {% else %}
                <p>This bread needs ingredients! <br> Go inside to get your hand dirty and make some bread.</p>
            {% endif %}
        </section>
    </div>
</body>
</html>